version: "3.4"
services:
  redis:
    image: redis:3.2
  db:
    restart: always
    image: mariadb:10.3
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
  web:
    restart: always
    volumes:
      - /data/www-provisioned/Web/_Resources
    image: ghcr.io/psmb/ermdistr:master
    networks:
      - default
      - main
    environment:
      - AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      - AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      - IMPORT_GITHUB_PUB_KEYS: 'dimaip,zaveryukha'
    labels:
      - "neos"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
      - "traefik.docker.network=main"
      - "traefik.frontend.rule=Host:ermolaev.co,dev.ermolaev.co,www.ermolaev.co"
    ports:
      - '80'
      - '1124:22'
    depends_on:
      - db
      - redis
volumes:
  db-data:
networks:
  main:
    external:
      name: main
