dbdata:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /var/lib/mysql

db:
  image: million12/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - dbdata
  environment:
    MARIADB_PASS: pass
  restart: always

webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
    - /data
    - ./Persistent:/data/www/shared/Data/Persistent
    - /etc/localtime:/etc/localtime:ro

web:
  image: dimaip/neos-bare
  ports:
    - '80'
  links:
    - db:db
  volumes_from:
    - webdata
  environment:
    VIRTUAL_HOST: 'ermolaev.co,dev.ermolaev.co,next.ermolaev.co,www.ermolaev.co'
    REPOSITORY_URL: 'https://github.com/sfi-ru/ErmDistr'
  restart: always

ssh:
  image: million12/php-app-ssh
  ports:
    - '1124:22'
  links:
    - db:db
    - web:web
  volumes_from:
    - webdata
  environment:
    IMPORT_GITHUB_PUB_KEYS: dimaip
  restart: always
