
Neos:
  Neos:
    nodeTypes:
      groups:
        contentBlocks:
          position: 110
          label: 'Content Blocks'
        contentWidgets:
          position: 120
          label: 'Content Widgets'
    fusion:
      autoInclude:
        Sfi.Widgets: true
