
TYPO3:
  Neos:
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
      inspector:
        dataTypes:
          Neos\Media\Domain\Model\ImageInterface:
            editorOptions:
              crop:
                aspectRatio:
                  options:
                    fourFive: null
                    fiveSeven: null
                    sixteenNine: null
                  enableOriginal: true
                  allowCustom: true
                  locked:
                    width: 0
                    height: 0
Neos:
  Flow:
    i18n:
      defaultLocale: ru
    http:
      baseUri: 'https://ermolaev.co/'
