TYPO3:
  Flow:
    i18n:
      defaultLocale: 'ru'
    http:
      baseUri: 'https://ermolaev.co/'
  Neos:
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
      inspector:
        dataTypes:
          'TYPO3\Media\Domain\Model\ImageInterface':
            editorOptions:
              crop:
                aspectRatio:
                  options:
                    fourFive: ~
                    fiveSeven: ~
                    sixteenNine: ~
                  enableOriginal: TRUE
                  allowCustom: TRUE
                  locked:
                    width: 0
                    height: 0
