TYPO3:
  Neos:
    userInterface:
      inspector:
        dataTypes:
          'TYPO3\Media\Domain\Model\ImageVariant':
            editorOptions:
              crop:
                aspectRatio:
                  options:
                    fourFive: ~
                    fiveSeven: ~
                    sixteenNine: ~
                  enableOriginal: TRUE
                  allowCustom: TRUE
                  locked:
                    width: 0
                    height: 0