
Neos:
  Flow:
    i18n:
      defaultLocale: ru
    resource:
      collections:
        persistent:
          storage: s3PersistentResourcesStorage
          target: s3PersistentResourcesTarget
      storages:
        s3PersistentResourcesStorage:
          storage: 'Flownative\Aws\S3\S3Storage'
          storageOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'storage/ermolaev/'
      targets:
        s3PersistentResourcesTarget:
          target: 'Flownative\Aws\S3\S3Target'
          targetOptions:
            bucket: 'psmb-neos-resources'
            keyPrefix: 'target/ermolaev/'
            baseUri: 'https://psmb-neos-resources.hb.bizmrg.com/target/ermolaev/'
  Neos:
    userInterface:
      navigateComponent:
        structureTree:
          loadingDepth: 0
        nodeTree:
          loadingDepth: 1
      inspector:
        dataTypes:
          Neos\Media\Domain\Model\ImageInterface:
            editorOptions:
              crop:
                aspectRatio:
                  options:
                    fourFive: null
                    fiveSeven: null
                    sixteenNine: null
                  enableOriginal: true
                  allowCustom: true
                  locked:
                    width: 0
                    height: 0
Flownative:
  Aws:
    S3:
      profiles:
        default:
          credentials:
            key: '%env:AWS_ACCESS_KEY_ID%'
            secret: '%env:AWS_SECRET_ACCESS_KEY%'
          endpoint: 'https://hb.bizmrg.com'
